### ISSUE TITLE
crypt.exe

### ISSUE THREAD

**Issue by candylol** [ssnob/T7-Compiler-UI#1]
came with this exe, it keeps running on startup and I cant uninstall it

**Comment by ssnob** [comment]
False positive!

**Comment by candylol** [comment]
I have heard of those before, I'm going to disable my anti virus then. thanks for the quick reply!
but, hey my pc is running slower than usual. it is a dell prebuilt pc.. so maybe that's it, but this is different.
the gpu is making a weird humming noise and its overheating???

**Comment by candylol** [comment]
Update here from my phone.
The plastic on my GT 710 is melting off and dripping into the power supply.

**Comment by ssnob** [comment]
Do you have any cooling?

**Comment by candylol** [comment]
Well, I did.. all the fans melted

sent from my iPhone

**Comment by shiversoftdev** [comment]
Hi, I installed this software and suddenly my PC asked me for monero? How do I buy a monero and how do I get it to you? I really need my files!
