### ISSUE TITLE
isdefined is broe

### ISSUE THREAD

**Issue by ApoIlos** [ssnob/T7-Compiler-UI#3]
Can't compile
![image](https://user-images.githubusercontent.com/65520840/170406108-cbb5088d-b5ce-4a02-ab44-840d98d2ce3f.png)
![image](https://user-images.githubusercontent.com/65520840/170406161-e9316205-3d6c-4076-8f84-be697454c774.png)

**Comment by ssnob** [comment]
skill issue

**Comment by ssnob** [comment]
I believe you should be using "fn" instead of function. Here is some compling/untested code: 
![image](https://user-images.githubusercontent.com/86132963/173479110-40817a37-f3a4-4479-ac52-acec4a6b9096.png)
